//
// Created by 何 义 on 14-4-12.
// Copyright (c) 2014 eall. All rights reserved.
//

//CLICK_CLIENT_SHARE,客户详情－分享,0
#define EVENT_CLICK_CLIENT_SHARE @"CLICK_CLIENT_SHARE"

//CLICK_HOUSE_SHARE,房源详情－分享,0
#define EVENT_CLICK_HOUSE_SHARE @"CLICK_HOUSE_SHARE"

//CLICK_HOUSE_SEARCH,房源－搜索,0
#define EVENT_CLICK_HOUSE_SEARCH @"CLICK_HOUSE_SEARCH"

//CLICK_CLIENT_SEARCH,客户－搜索,0
#define EVENT_CLICK_CLIENT_SEARCH @"CLICK_CLIENT_SEARCH"

//RESULT_CLIENT_SHARE,客户－分享结果,1
#define EVENT_RESULT_CLIENT_SHARE @"RESULT_CLIENT_SHARE"

//RESULT_HOUSE_SHARE,房源－分享结果,1
#define EVENT_RESULT_HOUSE_SHARE @"RESULT_HOUSE_SHARE"

//COUNT_HOUSE_SHARE,房源－分享数量,1
#define EVENT_COUNT_HOUSE_SHARE @"COUNT_HOUSE_SHARE"

//CLICK_FEATURED_HOUSE_LIST_SHARE,特选房源-分享,0
#define EVENT_CLICK_FEATURED_HOUSE_LIST_SHARE @"CLICK_FEATURED_HOUSE_LIST_SHARE"

//CLICK_ADD_FEATURED_HOUSE_FILTER,特选房源-添加特选条件,0
#define EVENT_CLICK_ADD_FEATURED_HOUSE_FILTER @"CLICK_ADD_FEATURED_HOUSE_FILTER"

//CLICK_EDIT_FEATURED_HOUSE_FILTER,特选房源-编辑特选条件,0
#define EVENT_CLICK_EDIT_FEATURED_HOUSE_FILTER @"CLICK_EDIT_FEATURED_HOUSE_FILTER"

//CLICK_HOUSE_MATCH_CLIENTS,房源详情-匹配客户,0
#define EVENT_CLICK_HOUSE_MATCH_CLIENTS @"CLICK_HOUSE_MATCH_CLIENTS"

//CLICK_HOUSE_MATCHED_CLIENT_LIST_MARK,房源详情-匹配客户-标记客户,0
#define EVENT_CLICK_HOUSE_MATCHED_CLIENT_LIST_MARK @"CLICK_HOUSE_MATCHED_CLIENT_LIST_MARK"

//CLICK_HOUSE_MARKED_CLIENTS,房源详情-已标记的客户,0
#define EVENT_CLICK_HOUSE_MARKED_CLIENTS @"CLICK_HOUSE_MARKED_CLIENTS"

//CLICK_HOUSE_VIEW_NUMBER,房源详情-查看电话,0
#define EVENT_CLICK_HOUSE_VIEW_NUMBER @"CLICK_HOUSE_VIEW_NUMBER"

//CLICK_RECENT_HOUSES,房源-最近查看,0
#define EVENT_CLICK_RECENT_HOUSES @"CLICK_RECENT_HOUSES"

//CLICK_HOUSE_FILTER,房源-筛选,0
#define EVENT_CLICK_HOUSE_FILTER @"CLICK_HOUSE_FILTER"

//CLICK_CLIENT_MATCH_HOUSES,客户详情-匹配房源,0
#define EVENT_CLICK_CLIENT_MATCH_HOUSES @"CLICK_CLIENT_MATCH_HOUSES"

//CLICK_CLIENT_MATCHED_HOUSE_LIST_MARK,客户详情-匹配房源-标记房源,0
#define EVENT_CLICK_CLIENT_MATCHED_HOUSE_LIST_MARK @"CLICK_CLIENT_MATCHED_HOUSE_LIST_MARK"

//CLICK_CLIENT_MARKED_CLIENTS,客户详情-已标记的房源,0
#define EVENT_CLICK_CLIENT_MARKED_CLIENTS @"CLICK_CLIENT_MARKED_CLIENTS"

//CLICK_CLIENT_VIEW_NUMBER,客户详情-查看电话,0
#define EVENT_CLICK_CLIENT_VIEW_NUMBER @"CLICK_CLIENT_VIEW_NUMBER"

//CLICK_RECENT_CLIENTS,客户-最近查看,0
#define EVENT_CLICK_RECENT_CLIENTS @"CLICK_RECENT_CLIENTS"

//CLICK_CLIENT_FILTER,客户-筛选,0
#define EVENT_CLICK_CLIENT_FILTER @"CLICK_CLIENT_FILTER"

//CLICK_IM_CONVERSATION,IM-对话列表-对话,0
#define EVENT_CLICK_IM_CONVERSATION @"CLICK_IM_CONVERSATION"

//CLICK_IM_CONVERSATION_REPLY,IM-对话列表-对话-回复,0
#define EVENT_CLICK_IM_CONVERSATION_REPLY @"CLICK_IM_CONVERSATION_REPLY"

//CLICK_IM_CONVERSATION_SEND_NEW_PHOTO,0,IM-对话-发送图片-拍照,0
#define EVENT_CLICK_IM_CONVERSATION_SEND_NEW_PHOTO @"CLICK_IM_CONVERSATION_SEND_NEW_PHOTO"

//CLICK_IM_CONVERSATION_SEND_EXISTING_PHOTO,0,IM-对话-发送图片-选择照片,0
#define EVENT_CLICK_IM_CONVERSATION_SEND_EXISTING_PHOTO @"CLICK_IM_CONVERSATION_SEND_EXISTING_PHOTO"

//CLICK_IM_SEND_HOUSE,IM-发送房源,0
#define EVENT_CLICK_IM_SEND_HOUSE @"CLICK_IM_SEND_HOUSE"

//CLICK_IM_SEND_CLIENT,IM-发送客户,0
#define EVENT_CLICK_IM_SEND_CLIENT @"CLICK_IM_SEND_CLIENT"

//CLICK_IM_COMPOSE,IM-撰写新消息,0
#define EVENT_CLICK_IM_COMPOSE @"CLICK_IM_COMPOSE"

//CLICK_IM_CONVERSATION_DELETE,IM-对话列表-删除对话,0
#define EVENT_CLICK_IM_CONVERSATION_DELETE @"CLICK_IM_CONVERSATION_DELETE"

//CLICK_IM_CONVERSATION_INFO,IM-对话-对话信息，0
#define EVENT_CLICK_IM_CONVERSATION_INFO @"CLICK_IM_CONVERSATION_INFO"

//CLICK_IM_CONVERSATION_INFO_ADD_MEMBER,IM-对话-对话信息-添加成员,0
#define EVENT_CLICK_IM_CONVERSATION_INFO_ADD_MEMBER @"CLICK_IM_CONVERSATION_INFO_ADD_MEMBER"

//CLICK_IM_CONVERSATION_INFO_REMOVE_MEMBER,IM-对话-对话信息-移除成员,0
#define EVENT_CLICK_IM_CONVERSATION_INFO_REMOVE_MEMBER @"CLICK_IM_CONVERSATION_INFO_REMOVE_MEMBER"

//CLICK_IM_CONVERSATION_INFO_SAVE_GROUP,IM-对话-对话信息-保存群,0
#define EVENT_CLICK_IM_CONVERSATION_INFO_SAVE_GROUP @"CLICK_IM_CONVERSATION_INFO_SAVE_GROUP"

//CLICK_IM_CONVERSATION_INFO_NOTIFICATION_OFF,IM-对话-对话信息-关闭通知,0
#define EVENT_CLICK_IM_CONVERSATION_INFO_NOTIFICATION_OFF @"CLICK_IM_CONVERSATION_INFO_NOTIFICATION_OFF"

//CLICK_IM_CONVERSATION_INFO_NOTIFICATION_ON,IM-对话-对话信息-开启通知,0
#define EVENT_CLICK_IM_CONVERSATION_INFO_NOTIFICATION_ON @"CLICK_IM_CONVERSATION_INFO_NOTIFICATION_ON"

//CLICK_IM_CONVERSATION_INFO_RENAME_GROUP,IM-对话-对话信息-修改群名称,0
#define EVENT_CLICK_IM_CONVERSATION_INFO_RENAME_GROUP @"CLICK_IM_CONVERSATION_INFO_RENAME_GROUP"

//CLICK_IM_CONVERSATION_INFO_CLEAR_HISTORY,IM-对话-对话信息-清空聊天记录,0
#define EVENT_CLICK_IM_CONVERSATION_INFO_CLEAR_HISTORY @"CLICK_IM_CONVERSATION_INFO_CLEAR_HISTORY"

//CLICK_IM_CONVERSATION_INFO_QUIT,IM-对话-对话信息-退群,0
#define EVENT_CLICK_IM_CONVERSATION_INFO_QUIT @"CLICK_IM_CONVERSATION_INFO_QUIT"

//CLICK_IM_SEND_TO_EALL,IM-对话-发给中环经纪人助手,0
#define EVENT_CLICK_IM_SEND_TO_EALL @"CLICK_IM_SEND_TO_EALL"

//CLICK_IM_SEND_TO_COMPANY,IM-对话-发给公司,0
#define EVENT_CLICK_IM_SEND_TO_COMPANY @"CLICK_IM_SEND_TO_COMPANY"

//CLICK_QRCODE_SCANNER,扫描二维码,0
#define EVENT_CLICK_QRCODE_SCANNER @"CLICK_QRCODE_SCANNER"

//CLICK_LOAN_CALCULATOR,贷款计算器,0
#define EVENT_CLICK_LOAN_CALCULATOR @"CLICK_LOAN_CALCULATOR"

//CLICK_COLLEAGUE_ADDRESSBOOK,同事通讯录,0
#define EVENT_CLICK_COLLEAGUE_ADDRESSBOOK @"CLICK_COLLEAGUE_ADDRESSBOOK"

//CLICK_COLLEAGUE_ADDRESSBOOK_SEARCH,同事通讯录-搜索,0
#define EVENT_CLICK_COLLEAGUE_ADDRESSBOOK_SEARCH @"CLICK_COLLEAGUE_ADDRESSBOOK_SEARCH"

//CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_CALL,同事通讯录-详情-拨打,0
#define EVENT_CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_CALL @"CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_CALL"

//CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SEND_SMS,同事通讯录-详情-发短信,0
#define EVENT_CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SEND_SMS @"CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SEND_SMS"

//CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SEND_MESSAGE,同事通讯录-详情-发内部消息,0
#define EVENT_CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SEND_MESSAGE @"CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SEND_MESSAGE"

//CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SAVE,同事通讯录-详情-保存,0
#define EVENT_CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SAVE @"CLICK_COLLEAGUE_ADDRESSBOOK_DETAIL_SAVE"

//CLICK_SETTINGS_CHANGE_PASSWORD,设置-修改密码,0
#define EVENT_CLICK_SETTINGS_CHANGE_PASSWORD @"CLICK_SETTINGS_CHANGE_PASSWORD"

//CLICK_SETTINGS_LOG_OUT,设置-登出,0
#define EVENT_CLICK_SETTINGS_LOG_OUT @"CLICK_SETTINGS_LOG_OUT"

//RESULT_HOUSE_FEATURED_HOUSE_FILTER,特选房源-结果,1
#define EVENT_RESULT_HOUSE_FEATURED_HOUSE_FILTER @"RESULT_HOUSE_FEATURED_HOUSE_FILTER"

//RESULT_HOUSE_PERSONALIZED_FEATURED_HOUSE_FILTER,自订特选房源-结果,1
#define EVENT_RESULT_HOUSE_PERSONALIZED_FEATURED_HOUSE_FILTER @"RESULT_HOUSE_PERSONALIZED_FEATURED_HOUSE_FILTER"

//RESULT_HOUSE_FILTER_RESULT,房源-筛选-结果,1
#define EVENT_RESULT_HOUSE_FILTER_RESULT @"RESULT_HOUSE_FILTER_RESULT"

//RESULT_HOUSE_MATCH_CLIENTS,房源详情-匹配客户-结果,1
#define EVENT_RESULT_HOUSE_MATCH_CLIENTS @"RESULT_HOUSE_MATCH_CLIENTS"

//RESULT_HOUSE_SEARCH,房源-搜索-结果,1
#define EVENT_RESULT_HOUSE_SEARCH @"RESULT_HOUSE_SEARCH"

//RESULT_CLIENT_FILTER_RESULT,客户-筛选-结果,1
#define EVENT_RESULT_CLIENT_FILTER_RESULT @"RESULT_CLIENT_FILTER_RESULT"

//RESULT_CLIENT_MATCH_HOUSES,客户详情-匹配房源-结果,1
#define EVENT_RESULT_CLIENT_MATCH_HOUSES @"RESULT_CLIENT_MATCH_HOUSES"

//RESULT_CLIENT_SEARCH,客户-搜索-结果,1
#define EVENT_RESULT_CLIENT_SEARCH @"RESULT_CLIENT_SEARCH"

//RESULT_ADDRESSBOOK_SEARCH,同事通讯录-搜索-结果,1
#define EVENT_RESULT_ADDRESSBOOK_SEARCH @"RESULT_ADDRESSBOOK_SEARCH"

//RESULT_QRCODE_SCANNER,二维码扫描-结果,1
#define EVENT_RESULT_QRCODE_SCANNER @"RESULT_QRCODE_SCANNER"

//房源详情-带看记录,0
#define EVENT_CLICK_TAKE_LOOK_RECORDS @"CLICK_TAKE_LOOK_RECORDS"

//房源详情-同小区房源,0
#define EVENT_CLICK_HOUSE_SAME_DISTRICT @"CLICK_HOUSE_SAME_DISTRICT"

//房源-跟进记录
#define EVENT_CLICK_HOUSE_MARKED_GJ_LIST @"CLICK_HOUSE_MARKED_GJ_LIST"

//!房源－跟进－新增
#define EVENT_CLICK_HOUSE_MARKED_GJ_LIST_ADD @"CLICK_HOUSE_MARKED_GJ_LIST_ADD"

//!房源详情－上传照片
#define EVENT_CLICK_HOUSE_UPLOAD @"CLICK_HOUSE_UPLOAD"

//!房源详情已收藏
#define EVENT_CLICK_HOUSE_VIEW_FAVORITES @"CLICK_HOUSE_VIEW_FAVORITES"

//!房源详情－隐号通话
#define EVENT_CLICK_HOUSE_MARKED_ANONYMOUSE @"CLICK_HOUSE_MARKED_ANONYMOUSE"

//!客户详情－跟进记录
#define EVENT_CLICK_CLIENT_VIEW_GJ_LIST @"CLICK_CLIENT_VIEW_GJ_LIST"

//!客户详情－跟进－增加
#define EVENT_CLICK_CLIENT_VIEW_GJ_LIST_ADD @"CLICK_CLIENT_VIEW_GJ_LIST_ADD"

//客户详情－邀请看房
#define EVENT_CLICK_CLIENT_INVITE @"CLICK_CLIENT_INVITE"

//客户详情－隐号通话
#define EVENT_CLICK_CLIENT_VIEW_ANONYMOUSE @"CLICK_CLIENT_VIEW_ANONYMOUSE"

//设置－隐号通话状态
#define EVENT_CLICK_SETTINGS_ANONYMOUSE_PHONE @"CLICK_SETTINGS_ANONYMOUSE_PHONE"

//设置－隐号－修改
#define EVENT_CLICK_SETTINGS_CHANGE_ANONYMOUSE_PHONE @"CLICK_SETTINGS_CHANGE_ANONYMOUSE_PHONE"

//IM-对话-新房客户跟进提醒
#define EVENT_CLICK_IM_NEW_HOUSE_REMIND @"CLICK_IM_NEW_HOUSE_REMIND"

//房源详情-编辑房源信息
#define EVENT_CLICK_HOUSE_EDIT  @"CLICK_HOUSE_EDIT"

//房源详情-变更推荐标签
#define EVENT_CLICK_HOUSE_CHANGE_TAGS  @"CLICK_HOUSE_CHANGE_TAGS"

//房源详情-变更状态
#define EVENT_CLICK_HOUSE_CHANGE_STATUS @"CLICK_HOUSE_CHANGE_STATUS"

//房源详情-带看记录
#define EVENT_CLICK_HOUSE_TAKE_LOOK @"CLICK_HOUSE_TAKE_LOOK"

//房源详情-举报
#define EVENT_CLICK_HOUSE_REPORT @"CLICK_HOUSE_REPORT"

//房源-新增
#define EVENT_CLICK_HOUSE_ADD @"CLICK_HOUSE_ADD"

//客户详情-编辑客户信息
#define EVENT_CLICK_CLIENT_EDIT @"CLICK_CLIENT_EDIT"

//客户详情-变更推荐标签
#define EVENT_CLICK_CLIENT_CHANGE_TAGS @"CLICK_CLIENT_CHANGE_TAGS"

//客户详情-变更状态
#define EVENT_CLICK_CLIENT_CHANGE_STATUS @"CLICK_CLIENT_CHANGE_STATUS"

//客户详情-带看记录
#define EVENT_CLICK_CLIENT_TAKE_LOOK @"CLICK_CLIENT_TAKE_LOOK"

//客户详情-带看记录-新增带看记录
#define EVENT_CLICK_CLIENT_TAKE_LOOK_ADD @"CLICK_CLIENT_TAKE_LOOK_ADD"

//客户-新增
#define EVENT_CLICK_CLIENT_ADD @"CLICK_CLIENT_ADD"

//客户-已收藏
#define EVENT_CLICK_CLIENT_FAVORITES @"CLICK_CLIENT_FAVORITES"

//新房
#define EVENT_CLICK_NEW_HOUSE @"CLICK_NEW_HOUSE"

//新房-分享
#define EVENT_CLICK_NEW_HOUSE_SHARE @"CLICK_NEW_HOUSE_SHARE"

//新房客户跟进
#define EVENT_CLICK_NEW_HOUSE_FOLLOW @"CLICK_NEW_HOUSE_FOLLOW"

//新房客户跟进-已报备
#define EVENT_CLICK_NEW_HOUSE_FOLLOW_SUBMITED @"CLICK_NEW_HOUSE_FOLLOW_SUBMITED"

//新房客户跟进-已成交
#define EVENT_CLICK_NEW_HOUSE_FOLLOW_DONE @"CLICK_NEW_HOUSE_FOLLOW_DONE"

//新房客户跟进-已带看
#define EVENT_CLICK_NEW_HOUSE_FOLLOW_LOOKED @"CLICK_NEW_HOUSE_FOLLOW_LOOKED"

//新房-申请报备
#define EVENT_CLICK_NEW_HOUSE_SUBMIT @"CLICK_NEW_HOUSE_SUBMIT"

//1.4
//房源详情-传播-发布到端⼝口
#define EVENT_CLICK_HOUSE_SHARE_POST @"CLICK_HOUSE_SHARE_POST"

//采房/发房
#define EVENT_CLICK_COLLECT_POST @"CLICK_COLLECT_POST"

//采房/发房-采集
#define EVENT_CLICK_COLLECT_POST_COLLECT @"CLICK_COLLECT_POST_COLLECT"

//采房/发房-订阅
#define EVENT_CLICK_COLLECT_POST_SUBSCRIBE @"CLICK_COLLECT_POST_SUBSCRIBE"

//采房/发房-书签
#define EVENT_CLICK_COLLECT_POST_BOOKMARK @"CLICK_COLLECT_POST_BOOKMARK"

//采房/发房-订阅-添加订阅条件
#define EVENT_CLICK_COLLECT_POST_SUBSCRIBE_ADD @"CLICK_COLLECT_POST_SUBSCRIBE_ADD"

//采房/发房-订阅-编辑订阅条件
#define EVENT_CLICK_COLLECT_POST_SUBSCRIBE_EDIT @"CLICK_COLLECT_POST_SUBSCRIBE_EDIT"

//采房/发房-采集-采集设置
#define EVENT_CLICK_COLLECT_POST_COLLECT_SETTING @"CLICK_COLLECT_POST_COLLECT_SETTING"

//采房/发房-采集-采集设置-投票
#define EVENT_CLICK_COLLECT_POST_COLLECT_SETTING_VOTE @"CLICK_COLLECT_POST_COLLECT_SETTING_VOTE"

//采房/发房-采集-房源详情
#define EVENT_CLICK_COLLECT_POST_COLLECT_HOUSE @"CLICK_COLLECT_POST_COLLECT_HOUSE"

//采房/发房-采集-房源详情-拨打电话
#define EVENT_CLICK_COLLECT_POST_COLLECT_HOUSE_CALL @"CLICK_COLLECT_POST_COLLECT_HOUSE_CALL"

//采房/发房-采集-房源详情-录⼊入 ERP
#define EVENT_CLICK_COLLECT_POST_COLLECT_HOUSE_ADD @"CLICK_COLLECT_POST_COLLECT_HOUSE_ADD"

//采房/发房-采集-房源详情-发布到端⼝口
#define EVENT_CLICK_COLLECT_POST_COLLECT_HOUSE_POST @"CLICK_COLLECT_POST_COLLECT_HOUSE_POST"

//采房/发房-采集-房源详情-书签
#define EVENT_CLICK_COLLECT_POST_COLLECT_HOUSE_BOOKMARK @"CLICK_COLLECT_POST_COLLECT_HOUSE_BOOKMARK"

//采房/发房-采集-房源详情-举报
#define EVENT_CLICK_COLLECT_POST_COLLECT_HOUSE_REPORT @"CLICK_COLLECT_POST_COLLECT_HOUSE_REPORT"

//采房/发房-已录⼊入ERP
#define EVENT_CLICK_COLLECT_POST_ADDED_ERP @"CLICK_COLLECT_POST_ADDED_ERP"

//采房/发房-发布记录
#define EVENT_CLICK_COLLECT_POST_POSTED @"CLICK_COLLECT_POST_POSTED"

//采房/发房-预约发布
#define EVENT_CLICK_COLLECT_POST_BOOKING @"CLICK_COLLECT_POST_BOOKING"

//采房/发房-发房端⼝口
#define EVENT_CLICK_COLLECT_POST_POST_PORT @"CLICK_COLLECT_POST_POST_PORT"

//采房/发房-发房端⼝口-投票
#define EVENT_CLICK_COLLECT_POST_POST_PORT_VOTE @"CLICK_COLLECT_POST_POST_PORT_VOTE"


//查询了多少次交易系统
#define EVENT_CLICK_TRADE @"CLICK_TRADE"

